spring:
  config:
    import: classpath:application-key.yml
  application:
    name: board
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.descriptor.sql.BasicBinder: trace